config/routes.rb
Rails.application.routes.draw do

  root :to => redirect('/cms') 

  namespace :cms do
    root to: 'articles#index'

    namespace :parsing do
      # tasks
      resources :tasks, only: %i[index new edit create update] do
        # pages
        get 'page/:id', to: 'pages#show', as: 'page'
        get 'page/:id/body', to: 'pages#body', as: 'page_body'
        resources :pages, only: %i[index] do
          # articles
          resources :articles, only: %i[index edit update]
        end
      end
      # articles
      get '/articles', to: 'articles#all', as: 'all_articles'
    end
    
    namespace :rewrite do
      # task_templates
      resources :task_templates, only: %i[index new edit create update]

      # tasks
      resources :tasks, only: %i[index new edit create update] do
        post 'publish', to: 'tasks#publish', as: 'publish'
      end
      post 'change_template_on_task_form', to: 'tasks#change_template_on_form', as: 'change_template_on_task_form'
      get '/parsing_articles/:p_article_id/tasks', to: 'tasks#new', as: 'new_rewrite_task'
      
      # task results
      get '/tasks/:task_id/results', to: 'task_results#index', as: 'task_results'
      resources :task_results, only: %i[show] do
        post 'accept', to: 'task_results#accept', as: 'accept'
        patch 'decline', to: 'task_results#decline', as: 'decline'
      end
    end

    # articles
    resources :articles

    # proxies
    resources :proxies
    post 'parse_proxies', to: 'proxies#parse', as: 'parse_proxies'
  end

  namespace :api do
  
    resources :articles, only: %i[index show]

  end
    
end

app/controllers/cms/articles_controller.rb
class Cms::ArticlesController < CmsController
  include BootstrapTable

  add_breadcrumb('Articles', :cms_articles_path)
  before_action :table_headers, only: %i[index]
  before_action :form_fields, only: %i[edit update new create]

  def index
    args = pagination_params
    @articles = Article.page(args[:page]).per(args[:per])
    @total = Article.count
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    result = ::Rewrite::Task::Result.find(params[:result_id])
    redirect_to(action: :edit, id: result.article.id) and return if result.article

    add_breadcrumb('New', :new_cms_article_path)
    @article = result.initialize_article
  rescue ActiveRecord::RecordNofFound
    redirect_to(action: :index)
  end

  def create
    @article = Article.new(article_params)
    # TODO: сделать нормальную систему публикации
    @article.publish_at = DateTime.now
    @article.save!
    redirect_to(action: :index)
  rescue ActiveRecord::RecordInvalid => e
    add_breadcrumb('New', :new_cms_article_path)
    @errors = e.record.errors.messages
    render(action: :new)
  end

  def edit
    @article = Article.find(params[:id])
    add_breadcrumb(@article.title, edit_cms_article_path(@article.id))
  rescue ActiveRecord::RecordNofFound
    redirect_to(action: :index)
  end

  def update
    @article = Article.find(params[:id])
    @article.update!(article_params)
    redirect_to(action: :index)
  rescue ActiveRecord::RecordNofFound
    redirect_to(action: :index)
  rescue ActiveRecord::RecordInvalid => e
    add_breadcrumb(@article.title, edit_cms_article_path(@article.id))
    @errors = e.record.errors.messages
    render(action: :edit)
  end

  # TODO: добавить обработчик неудачного удаления
  def destroy
    @article = Article.find(params[:id])
    @article.destroy!
    redirect_to(action: :index)
  rescue ActiveRecord::RecordNofFound
    redirect_to(action: :index)
  end

  private

    def article_params
      params.require(:article).permit(:title, :description, :body, :status, :rewrite_task_result_id)
    end

    def table_headers
      @table_headers = [{
        field: 'id',
        title: '#',
      }, {
        field: 'title',
        title: 'Title',
      }, {
        field: 'status',
        title: 'Status',
      }, {
        field: 'publish_at',
        title: 'Publish at',
      },]
    end

    # Поля для формы
    def form_fields
      @form_fields = [
        {
          type: FormFieldType::HIDDEN,
          key: :rewrite_task_result_id,
        },
        {
          type: FormFieldType::TEXT_FIELD,
          key: :title,
          label: 'Title',
        },
        {
          type: FormFieldType::TEXT_FIELD,
          key: :description,
          label: 'Description',
        },
        {
          type: FormFieldType::RICH_TEXT,
          key: :body,
          label: 'Body',
          id: 'article_body',
        },
        {
          type: FormFieldType::SELECT,
          key: :status,
          label: 'Status',
          include_blank: false,
          options: ::Article::STATUS_SELECT_OPTIONS,
        },
      ]
    end
end

app/controllers/cms/parsing/articles_controller.rb
class Cms::Parsing::ArticlesController < CmsController
  include BootstrapTable

  before_action :table_headers, only: %i[index all]
  before_action :form_fields, only: %i[edit update]

  def index
    @page = ::Parsing::Page.find_by!(id: params[:page_id], task_id: params[:task_id])
    args = pagination_params
    @articles = @page.articles.page(args[:page]).per(args[:per])
    @total = @page.articles.count
    basic_breadcrumbs(@page)
  rescue ActiveRecord::RecordNotFound
    redirect_to(:cms_parsing_tasks_path)
  end

  def all
    args = pagination_params
    @articles = ::Parsing::Article.active.page(args[:page]).per(args[:per])
    @total = ::Parsing::Article.count
    add_breadcrumb('Articles', :cms_parsing_all_articles_path)
  end

  def edit
    @article = ::Parsing::Article.find(params[:id])
    basic_breadcrumbs(@article.page)
    add_breadcrumb(@article.id, edit_cms_parsing_task_page_article_path(@article))
  rescue ActiveRecord::RecordNotFound
    redirect_to(:cms_parsing_tasks_path)
  end

  def update
    @article = ::Parsing::Article.find(params[:id])
    basic_breadcrumbs(@article.page)
    add_breadcrumb(@article.id, edit_cms_parsing_task_page_article_path(@article))
    @article.update!(article_params)
    redirect_to(action: :index, page_id: @article.page_id, task_id: @article.page.task_id)
  rescue ActiveRecord::RecordNotFound
    redirect_to(action: :index, page_id: @article.page_id, task_id: @article.page.task_id)
  rescue ActiveRecord::RecordInvalid => e
    @errors = e.record.errors.messages
    render(action: :edit)
  end

  private

    # Хедеры для таблицы на странице index
    def table_headers
      @table_headers = [{
        field: 'id',
        title: '#',
      }, {
        field: 'address',
        title: 'Address',
      }, {
        field: 'status',
        title: 'Status',
      }, {
        field: 'edit',
        title: 'Edit',
      },]
    end

    # Поля для формы8080
    def form_fields
      @form_fields = [{
        type: FormFieldType::RADIO_BUTTON,
        key: :status,
        buttons: [{
          value: ::Parsing::Article::NEW,
          label: 'New',
        }, {
          value: ::Parsing::Article::NOT_ARTICLE,
          label: 'Not article',
        }, {
          value: ::Parsing::Article::FOR_REWRITE,
          label: 'For rewrite',
        }, {
          value: ::Parsing::Article::SENT_TO_REWRITE,
          label: 'Sent to rewrite',
        }, {
          value: ::Parsing::Article::REWRITED,
          label: 'Rewrited',
        },],
      }, {
        type: FormFieldType::TEXT_FIELD,
        key: :title,
        label: 'Title'
      }, {
        type: FormFieldType::TEXT_AREA,
        key: :body,
        label: 'Body',
      },]
    end

    def basic_breadcrumbs(page)
      add_breadcrumb('Parsing tasks', :cms_parsing_tasks_path)
      add_breadcrumb(page.task.host, edit_cms_parsing_task_path(page.task_id))
      add_breadcrumb('Pages', cms_parsing_task_pages_path(task_id: page.task_id))
      add_breadcrumb('Articles', cms_parsing_task_page_articles_path(task_id: page.task_id, page_id: page.id))
    end

    def article_params
      params.require(:parsing_article).permit(:html, :status, :title, :body)
    end
end

app/controllers/cms/parsing/pages_controller.rb
class Cms::Parsing::PagesController < CmsController
  include BootstrapTable

  before_action :table_headers, only: %i[index]

  layout :resolve_layout

  def index
    @task = ::Parsing::Task.find(params[:task_id])
    args = pagination_params
    @pages = @task.pages.page(args[:page]).per(args[:per])
    @total = @task.pages.count
    basic_breadcrumbs(@task)
  rescue ActiveRecord::RecordNotFound
    redirect_to(:cms_parsing_tasks_path)
  end

  def show
    @page = ::Parsing::Page.find_by!(id: params[:id], task_id: params[:task_id])
    basic_breadcrumbs(@page.task)
    add_breadcrumb(@page.address, cms_parsing_task_page_path(id: @page.id, task_id: @page.task_id))
  rescue ActiveRecord::RecordNotFound
    redirect_to(:cms_parsing_tasks_path)
  end

  def body
    page = ::Parsing::Page.find_by!(id: params[:id], task_id: params[:task_id])
    @body = page.body
  rescue ActiveRecord::RecordNotFound
    redirect_to(:cms_parsing_tasks_path)
  end

  private

    def resolve_layout
      'blank' if action_name == 'body'
    end

    # Хедеры для таблицы на странице index
    def table_headers
      @table_headers = [{
        field: 'id',
        title: '#',
      }, {
        field: 'address',
        title: 'Address',
      }, {
        field: 'hrefs_has_been_parsed',
        title: 'Hrefs parsed',
      }, {
        field: 'articles_has_been_parsed',
        title: 'Articles parsed',
      }, {
        field: 'articles',
        title: 'Articles',
      }, {
        field: 'body',
        title: 'Содержание',
      },]
    end

    def basic_breadcrumbs(task)
      add_breadcrumb('Parsing tasks', :cms_parsing_tasks_path)
      add_breadcrumb(task.host, edit_cms_parsing_task_path(task))
      add_breadcrumb('Pages', cms_parsing_task_pages_path(task_id: task.id))
    end
end

app/controllers/cms/parsing/tasks_controller.rb
class Cms::Parsing::TasksController < CmsController
  include BootstrapTable

  add_breadcrumb('Parsing tasks', :cms_parsing_tasks_path)
  before_action :table_headers, only: %i[index]
  before_action :form_fields, only: %i[new edit update create]

  def index
    args = pagination_params
    @tasks = ::Parsing::Task.page(args[:page]).per(args[:per])
    @total = ::Parsing::Task.count

    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    add_breadcrumb('New task', :new_cms_parsing_task_path)
    @task = ::Parsing::Task.new
  end

  def create
    add_breadcrumb('New task', :new_cms_parsing_task_path)

    # Создание в 2 шага что бы передать форме валидные данные а не nil (в случае ошибки валидации)
    @task = ::Parsing::Task.new(task_params)
    @task.save!

    redirect_to(action: :index)
  rescue ActiveRecord::RecordInvalid => e
    @errors = e.record.errors.messages
    render(action: :new, status: 422)
  end

  def edit
    @task = ::Parsing::Task.find(params[:id])
    add_breadcrumb(@task.host, edit_cms_parsing_task_path(@task))
  rescue ActiveRecord::RecordNotFound
    redirect_to(:cms_parsing_tasks_path)
  end

  def update
    @task = ::Parsing::Task.find(params[:id])
    @task.update!(task_params)
    redirect_to(action: :index)
  rescue ActiveRecord::RecordNotFound
    render(nothing: true, status: 404)
  rescue ActiveRecord::RecordInvalid => e
    add_breadcrumb(e.record.host, edit_cms_parsing_task_path(@task))
    @errors = e.record.errors.messages
    render(action: :edit, status: 422)
  end

  private

    # Хедеры для таблицы на странице index
    def table_headers
      @table_headers = [{
        field: 'id',
        title: '#',
      }, {
        field: 'host',
        title: 'Host',
      }, {
        field: 'status',
        title: 'Status',
      }, {
        field: 'edit',
        title: 'Edit',
      }, {
        field: 'pages',
        title: 'Pages',
      },]
    end

    # Поля для формы
    def form_fields
      @form_fields = [{
        type: FormFieldType::TEXT_FIELD,
        key: :host,
        label: 'Host',
      }, {
        type: FormFieldType::TEXT_FIELD,
        key: :article_title_path,
        label: 'Article title path',
      }, {
        type: FormFieldType::TEXT_FIELD,
        key: :article_body_path,
        label: 'Article body path',
      }, {
        type: FormFieldType::TEXT_FIELD,
        key: :block_request_path,
        label: 'Article bad request path',
      }, {
        type: FormFieldType::TEXT_FIELD,
        key: :block_request_value,
        label: 'Article bad request value',
      }, {
        type: FormFieldType::RADIO_BUTTON,
        key: :status,
        buttons: [{
          value: ::Parsing::Task::INACTIVE,
          label: 'Inactive',
        }, {
          value: ::Parsing::Task::ACTIVE,
          label: 'Active',
        }, {
          value: ::Parsing::Task::ARCHIVED,
          label: 'Archived',
        },],
      },]
    end

    # Аргументы для создания и обновления таска
    def task_params
      params.require(:parsing_task)
            .permit(:host, :article_title_path, :article_body_path, :status, :block_request_path, :block_request_value)
    end
end

app/controllers/cms/proxies_controller.rb
class Cms::ProxiesController < CmsController
  include BootstrapTable

  add_breadcrumb('Proxies', :cms_proxies_path)
  before_action :table_headers, only: %i[index]
  before_action :form_fields, only: %i[edit update new create]

  def index
    args = pagination_params
    @proxies = Proxy.page(args[:page]).per(args[:per])
    @total = Proxy.count
    respond_to do |format|
      format.html
      format.json
    end
  end

  def new
    add_breadcrumb('New', :new_cms_proxy_path)
    @proxy = Proxy.new
  end

  def create
    @proxy = Proxy.new(proxy_params)
    @proxy.save!
    redirect_to(action: :index)
  rescue ActiveRecord::RecordInvalid => e
    add_breadcrumb('New', :new_cms_proxy_path)
    @errors = e.record.errors.messages
    render(action: :new)
  end

  def edit
    @proxy = Proxy.find(params[:id])
    add_breadcrumb(@proxy.full_address, edit_cms_proxy_path(@proxy))
  rescue ActiveRecord::RecordNofFound
    redirect_to(action: :index)
  end

  def update
    @proxy = Proxy.find(params[:id])
    @proxy.update!(proxy_params)
    redirect_to(action: :index)
  rescue ActiveRecord::RecordNofFound
    redirect_to(action: :index)
  rescue ActiveRecord::RecordInvalid => e
    add_breadcrumb(@proxy.full_address, edit_cms_article_path(@article.id))
    @errors = e.record.errors.messages
    render(action: :edit)
  end

  # TODO: добавить обработчик неудачного удаления
  def destroy
    @proxy = Proxy.find(params[:id])
    @proxy.destroy!
    redirect_to(action: :index)
  rescue ActiveRecord::RecordNofFound
    redirect_to(action: :index)
  end

  def parse
    Proxy.parse!
    redirect_to(action: :index)
  end

  private

    def proxy_params
      params.require(:proxy).permit(:ip, :port)
    end

    def table_headers
      @table_headers = [{
        field: 'id',
        title: '#',
      }, {
        field: 'full_address',
        title: 'Full address',
      },]
    end

    # Поля для формы
    def form_fields
      @form_fields = [
        {
          type: FormFieldType::TEXT_FIELD,
          key: :ip,
          label: 'IP',
        },
        {
          type: FormFieldType::NUMBER_FIELD,
          key: :port,
          label: 'Port',
        },
      ]
    end
end

app/controllers/cms/rewrite/task_results_controller.rb
class Cms::Rewrite::TaskResultsController < CmsController
  include BootstrapTable

  before_action :table_headers, only: %i[index]
  before_action :decline_form_fields, only: %i[show]

  def index
    task = ::Rewrite::Task.find(params[:task_id])
    basic_breadcrumbs(task)
    args = pagination_params
    @results = task.results.page(args[:page]).per(args[:per])
    @total = task.results.count
    respond_to do |format|
      format.html
      format.json
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to(cms_rewrite_tasks_path)
  end

  def show
    @result = ::Rewrite::Task::Result.find(params[:id])
    basic_breadcrumbs(@result.task)
    add_breadcrumb(@result.external_id, cms_rewrite_task_result_path(@result.id))
  rescue ActiveRecord::RecordNotFound
    redirect_to(cms_rewrite_tasks_path)
  end

  def accept
    @result = ::Rewrite::Task::Result.find(params[:task_result_id])
    @result.task.accept!
    redirect_to(edit_cms_rewrite_task_path(@result.task_id))
  rescue ActiveRecord::RecordNotFound
    redirect_to(cms_rewrite_tasks_path)
  end

  def decline
    @result = ::Rewrite::Task::Result.find(params[:task_result_id])
    ::Rewrite::Task::Result.transaction do
      @result.update!(result_params)
      @result.task.decline!
    end
    redirect_to(edit_cms_rewrite_task_path(@result.task_id))
  rescue ActiveRecord::RecordNotFound
    redirect_to(cms_rewrite_tasks_path)
  end

  private

    def result_params
      params.require(:rewrite_task_result).permit(:my_comment)
    end

    def basic_breadcrumbs(task)
      add_breadcrumb('Tasks', :cms_rewrite_tasks_path)
      add_breadcrumb(task.title, edit_cms_rewrite_task_path(task.id))
      add_breadcrumb('Results', cms_rewrite_task_results_path(task.id))
    end

    def table_headers
      @table_headers = [{
        field: 'id',
        title: '#',
      }, {
        field: 'external_id',
        title: 'External id',
      }, {
        field: 'made_at',
        title: 'Made at',
      }, {
        field: 'status',
        title: 'Status',
      },]
    end

    def decline_form_fields
      @form_fields = [
        {
          type: FormFieldType::TEXT_FIELD,
          key: :my_comment,
          label: 'Comment',
        },
      ]
    end
end

app/views/cms/_form.html.erb
<% 
  errors ||= {} 
  url = url.nil? ? {action: action} : url
  btn_text ||= 'Save'
  btn_class ||= 'btn btn-success'
%>
<%= form_for(record, url: url) do |f| %>
  <% fields.each do |field| %>
    <% case field[:type] %>
    <% when FormFieldType::TEXT_FIELD %>
      <div class='form-group'>
        <%= f.label field[:key], field[:label] %>
        <%= f.text_field field[:key], class: "form-control #{errors[field[:key]].blank? ? '' : 'is-invalid'}", autocomplete: :off %>
        <div class="invalid-feedback">
          <%= (errors[field[:key]] || []).join(', ') %>
        </div>
      </div>
    <% when FormFieldType::TEXT_AREA %>
      <div class='form-group'>
        <%= f.label field[:key], field[:label] %>
        <%= f.text_area field[:key], rows: 10, class: "form-control #{errors[field[:key]].blank? ? '' : 'is-invalid'}", autocomplete: :off %>
        <div class="invalid-feedback">
          <%= (errors[field[:key]] || []).join(', ') %>
        </div>
      </div>
    <% when FormFieldType::CHECK_BOX %>
      <div class='form-group form-check'>
        <%= f.check_box field[:key], class: "form-check-input #{errors[field[:key]].blank? ? '' : 'is-invalid'}" %>
        <%= f.label field[:key], field[:label], class: 'form-check-label' %>
        <div class="invalid-feedback">
          <%= (errors[field[:key]] || []).join(', ') %>
        </div>
      </div>
    <% when FormFieldType::RADIO_BUTTON %>
      <div class='form-group'>
        <label>Status</label>
        <% field[:buttons].each do |button| %>
          <div class='form-check'>
            <%= f.radio_button field[:key], button[:value], class: "form-check-input #{errors[field[:key]].blank? ? '' : 'is-invalid'}" %>
            <%= f.label field[:key], button[:label], class: 'form-check-label' %>
            <div class="invalid-feedback">
              <%= (errors[field[:key]] || []).join(', ') %>
            </div>
          </div>
        <% end %>
      </div>
    <% when FormFieldType::NUMBER_FIELD %>
      <div class='form-group'>
        <%= f.label field[:key], field[:label] %>
        <%= f.number_field field[:key], class: "form-control #{errors[field[:key]].blank? ? '' : 'is-invalid'}", autocomplete: :off %>
        <div class="invalid-feedback">
          <%= (errors[field[:key]] || []).join(', ') %>
        </div>
      </div>
    <% when FormFieldType::SELECT %>
      <div class='form-group'>
        <%= f.label field[:key], field[:label] %>
        <%= f.select field[:key], field[:options], { include_blank: field[:include_blank] }, class: "form-control #{errors[field[:key]].blank? ? '' : 'is-invalid'}" %>
        <div class="invalid-feedback">
          <%= (errors[field[:key]] || []).join(', ') %>
        </div>
      </div>
    <% when FormFieldType::RICH_TEXT %>
      <div class='form-group'>
        <%= f.label field[:key], field[:label] %>
        <%= f.hidden_field field[:key], rows: 10, class: "form-control #{errors[field[:key]].blank? ? '' : 'is-invalid'}", autocomplete: :off, id: field[:id] %>
        <trix-editor input="<%= field[:id] %>"></trix-editor>
        <div class="invalid-feedback">
          <%= (errors[field[:key]] || []).join(', ') %>
        </div>
      </div>
    <% when FormFieldType::HIDDEN %>
      <%= f.hidden_field field[:key] %>
    <% end %>
    <%
      errors.delete(field[:key])
    %>
  <% end %>
  <% unless errors.blank? %>
    <div>
      <p>Other errors:</p>
      <% errors.each do |key, value| %>
        <p><%= "#{key}: #{value.join(', ')}" %></p>
      <% end %>
    </div>
  <% end %>
  <%= f.submit btn_text, class: btn_class %>
<% end %>

app/views/cms/_menu.html.erb
<div id="menu">
  <div>
    <a>Parsing</a>
    <div class="sub_menu">
      <%= link_to('Tasks', cms_parsing_tasks_path) %>
      <%= link_to('Articles', cms_parsing_all_articles_path) %>
    </div>
  </div>
  <div>
    <a>Rewrite</a>
    <div class="sub_menu">
      <%= link_to('Task templates', cms_rewrite_task_templates_path) %>
      <%= link_to('Tasks', cms_rewrite_tasks_path) %>
    </div>
  </div>
  <div>
    <%= link_to('Articles', cms_articles_path) %>
  </div>
  <div>
    <%= link_to('Proxies', cms_proxies_path) %>
  </div>
</div>

app/views/cms/_table.html.erb
<%
  side_pagination = defined?(side_pagination) ? side_pagination : 'client'
%>

<table
  id="tasks_table"
	class="table"
  data-toggle="table"
  data-url="<%= url %>"
  data-pagination="true"
  data-side-pagination="<%= side_pagination %>"
  data-page-size="25">
  <thead class="thead-dark">
    <tr>
      <% headers.each do |header| %>
        <th data-field="<%= header[:field] %>"><%= header[:title] %></th>
      <% end %>
    </tr>
  </thead>
</table>